version: "3.9"
services:

#  db:
#    container_name: pg_container
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: test_db
#    ports:
#      - "5432:5432"
#      
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    depends_on:
#      - db
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
#    depends_on:
#      - db
    ports:
      - "6000:6000"
    environment:
      PORT: 6000
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        BACKEND_PORT: 6000
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"
    environment:
      REACT_APP_API_URL: backend
